config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'posts#index'
  get 'post/search' => 'posts#search'

  resources :users
  resources :posts, only: [:index, :show, :create, :destroy] do
    resource :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :relationships
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: [:index, :create, :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :post

	validates :user_id, presence: true
	validates :post_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def create
		@fovorite = current_user.favorites.create(post_id: params[:post_id])
		@post = Post.find(params[:post_id])
		@post.create_notification_favorite!(current_user)
		respond_to do |format|
		    format.html { redirect_to @user }
		    format.js
		end
	end

	def destroy
		@fovorite = current_user.favorites.find_by(post_id: params[:id].to_i).destroy
		# @fovorite = current_user.find_by(post_id: params[:id].to_i).destroy
		@post = Post.find(params[:id])
		respond_to do |format|
		    format.html { redirect_to @user }
		    format.js
		end
	end

	private
	def favorite_params
		params.require(:favorite).permit(:user_id, :post_id)
	end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_like.html.erb
<% if post.favorite?(post, current_user) %>
	<div class="like_off">
		<% if post.user.id != current_user.id %>
			<%= link_to favorite_path(id: post.id), method: :delete, remote: true, class: "like_off_btn" do %>
				<i class="fas fa-heart faa-pulse animated" style="color: #FF6928;"></i> <%= post.favorites.count %>
			<% end %>
		<% else %>
			<i class="fas fa-heart faa-pulse animated" style="color: #FF6928;"></i> <%= post.favorites.count %>
		<% end %>
	</div>
<% else %>
	<div class="like_on">
		<% if post.user.id != current_user.id %>
			<%= link_to favorites_path(post_id: post.id), method: :post, remote: true, class: "like_on_btn" do %>
				<i class="far fa-heart"></i> <%= post.favorites.count %>
			<% end %>
		<% else %>
			<i class="fas fa-heart faa-pulse animated" style="color: #FF6928;"></i> <%= post.favorites.count %>
		<% end %>
	</div>
<% end %>

app/views/favorites/create.js.erb
$(".favorite_btn_<%= @post.id %>").html("<%= escape_javascript(render partial: 'favorites/like', locals: { post: @post }) %>")

app/views/favorites/destroy.js.erb
$(".favorite_btn_<%= @post.id %>").html("<%= escape_javascript(render partial: 'favorites/like', locals: { post: @post }) %>")