config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'posts#index'
  get 'post/search' => 'posts#search'

  resources :users
  resources :posts, only: [:index, :show, :create, :destroy] do
    resource :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :relationships
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: [:index, :create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user
	belongs_to :post
	has_many :notifications, dependent: :destroy

	mount_uploader :comment_image, CommentImageUploader
	mount_uploader :comment_video, CommentVideoUploader

	validates :body, presence: true, length: { maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy]

	def create
        @post = Post.find(params[:post_id])
        @comment = current_user.comments.new(comment_params)
    	@comment.post_id = @post.id
        if  @comment.save
            render :index
        else
            "render posts/show"
    	end
    end

    def destroy
        @comment = Comment.find(params[:id])
        if @comment.destroy
            render :index
        end
        # redirect_back(fallback_location: root_path)
    end

    private
    	def comment_params
    		params.require(:comment).permit(:user_id, :post_id, :body, :comment_image, :comment_video)
        end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment-new.html.erb
<div class="card">
    <div class="card-body">
        <%= form_with(model: [@post, @comment] ) do |f| %>
			<div class="c-body">
				<%= f.text_area :body, class: "form-control", placeholder:"テキストの入力は必須です!!", rows: 3 %>
			</div>
			<div class="comment-ivs">
				<div class="c-img">
					<%=f.label :comment_image do %>
						<i class="fas fa-image fa-2x"></i>
						<%= f.file_field :comment_image, class:"np-img" %>
					<% end %>
				</div>
				<div class="c-video">
					<%=f.label :comment_video do %>
						<i class="fas fa-video fa-2x" style="margin-left: 60%;"></i>
						<%= f.file_field :comment_video, class:"np-img" %>
					<% end %>
				</div>
				<div class="c-submit">
					<input class="submit_button" type="submit" name="submit" value="コメントする">
				</div>
			</div>
		<% end %>
    </div>
</div>

app/views/comments/_index.html.erb
<div id="comment_index">
	<% comments.each do |comment| %>
		<div class="card" style="width: 100%;">
			<div class="card-header">
				<%= image_tag comment.user.profile_image.url, :size => '50x50' %>
				<%= link_to user_path(comment.user.id) do %>
					<%= comment.user.name %>
				<% end %>
				<% if user_signed_in? %>
					<% if comment.user != current_user %>
						<div class="follow-form<%= comment.user.id %>">
							<% if current_user.following?(comment.user) %>
							    <%= render 'relationships/unfollow', user: comment.user %>
							<% else %>
							    <%= render 'relationships/follow', user: comment.user %>
							<% end %>
						</div>
					<% end %>
					<% if comment.user == current_user %>
						<div><%= link_to "削除", comment_path(comment.id), method: :delete, remote: true, "data-confirm" => "コメントを削除しますか？" ,class: "btn btn-danger" %>
						</div>
					<% end %>
				<% end %>
			</div>
			<div class="card-body">
				<div class="post-body">
					<%= comment.body %>
				</div>
				<div class="post-img">
					<% if comment.comment_image.present? %>
						<%= image_tag comment.comment_image.url %>
					<% end %>
				</div>
				<div class="post-vid">
					<% if comment.comment_video.file.present? %>
						<%= video_tag comment.comment_video_url.to_s,autoplay: true, loop: true, controls: true %>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>
</div>

<script src="comment_reload.js"></script>

app/views/comments/index.js.erb
$("#comment-index").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('') //コメントのテキストをからにする