config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'posts#index'
  get 'post/search' => 'posts#search'

  resources :users
  resources :posts, only: [:index, :show, :create, :destroy] do
    resource :comments, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :relationships
  resources :favorites, only: [:create, :destroy]
  resources :notifications, only: [:index, :create, :destroy]
end

app/views/shares/_header.html.erb
<% if user_signed_in? %>
	<%= link_to user_path(current_user.id) do %>
		<h3>Posters</h3>
	<% end %>
	<div id="modal-overlay"></div>
	<div class="header-search">
		<%= form_tag(post_search_path,method: :get, role:"search") do %>
			<%= text_field_tag "keyword", "", {class:"form-control", placeholder:"キーワードで検索"}  %>
		<% end %>
	</div>
	<li id="modal-open-edit"><%= image_tag current_user.profile_image.url, :size => '40x40' %>
		<div class="edit">編集</div>
	</li>
	<div id="modal-content-edit">
		<%= render "users/edit" %>
	</div>
	<li id="modal-open-noti">
		<i class="fa fa-bell" aria-hidden="true">通知</i>
	</li>
	<div id="modal-content-noti">
		<%= render "notifications/notifi" %>
	</div>
	<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
<% else %>
	<%= link_to root_path do %>
		<h3>Posters</h3>
	<% end %>
	<li style="margin-top: 8px;"><%= link_to "ログイン", new_user_session_path %></li>
	<li style="margin-top: 8px;"><%= link_to "アカウント作成",new_user_registration_path %></li>
<% end %>

<script src="js/modal.js"></script>
<script src="js/edit.js"></script>

app/views/shares/_notifi.html.erb
<%= link_to notifications_path do %>
	<i class="fa fa-bell" aria-hidden="true">通知</i>
<% end %>

app/views/shares/_rside.html.erb
<div class="row">
	<% if user_signed_in? %>
		<%= form_for(@newpost) do |f| %>
			<div class="rside-newpost">
				<%= f.text_area :body, class: "form-control", placeholder:"テキストの入力は必須です!!", rows: 5 %>
			</div>
			<div class="rside-newimg">
				<%=f.label :post_image do %>
					<i class="fas fa-image fa-2x"></i>
					<%= f.file_field :post_image, class:"np-img" %>
				<% end %>
				<%=f.label :post_video do %>
					<i class="fas fa-video fa-2x" style="margin-left: 60%;"></i>
					<%= f.file_field :post_video, class:"np-img" %>
				<% end %>
				<input class="submit_button" type="submit" name="submit" value="投稿する">
			</div>
		<% end %>
		<div class="col-10 offset-2" style="margin-top: 40px;">
			<div class="rside-title">おすすめユーザー</div>
		</div>
		<% @follow_follows.each do |user| %>
			<table class="table table-hover" style="margin-bottom: 0;">
				<tr>
					<td>
						<div class="rside-user">
							<%= link_to user_path(user.id) do %>
								<%= image_tag user.profile_image.url, :size => '50x50' %>
								<%= user.name %>
							<% end %>
						</div>
					</td>
					<td style="text-align: right;">
						<% if current_user != user %>
							<div class="follow-form<%= user.id %>" style="margin-top: 4%;">
								<% if current_user.following?(user) %>
								    <%= render 'relationships/unfollow', user: user %>
								<% else %>
								    <%= render 'relationships/follow', user: user %>
								<% end %>
							</div>
						<% end %>
					</td>
				</tr>
			</table>
		<% end %>
	<% end %>
</div>

app/views/shares/_user-edit.html.erb
<%= link_to edit_user_path(current_user) do %>
	<%= image_tag current_user.profile_image.url, :size => '40x40' %>編集
<% end %>